stages:
  - lint
  - build
  - test

lint-clang-format:
  image: ubuntu:latest
  stage: lint
  script:
    - echo "No Impl."

build-gcc-debug:
  image: ubuntu:latest
  stage: build
  needs: []
  script:
    - apt update -y

    # Install Tools
    - apt install -y g++-12 make cmake
    - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 10
    - update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 10
    - update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 20
    - update-alternatives --set cc /usr/bin/gcc
    - update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 20
    - update-alternatives --set c++ /usr/bin/g++

    # Install Dependencies
    - apt install -y libgl1-mesa-dev libglu1-mesa-dev

    # Build
    - cmake --preset gcc-debug
    - cmake --build --preset gcc-debug
