stages:
  - lint
  - build
  - test

default:
  interruptible: true

variables:
  NUGET_SOURCE: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/nuget/index.json"
  NUGET_NAME: gitlab
  VCPKG_VERSION: 2024.10.21
  VCPKG_BINARY_SOURCES: "clear;nuget,${NUGET_NAME},readwrite"
  CMAKE_COMMAND: ${CI_PROJECT_DIR}/vcpkg/downloads/tools/cmake-3.30.1-linux/cmake-3.30.1-linux-x86_64/bin/cmake
  NUGET_COMMAND: ${CI_PROJECT_DIR}/vcpkg/downloads/tools/nuget-6.10.0-linux/nuget.exe

.get-vcpkg: &get-vcpkg
  # Get vcpkg
  - git clone https://github.com/microsoft/vcpkg.git --depth 1 --branch ${VCPKG_VERSION}
  - ./vcpkg/bootstrap-vcpkg.sh
  - ./vcpkg/vcpkg fetch nuget --x-wait-for-lock
  - ./vcpkg/vcpkg fetch cmake --x-wait-for-lock

  # Configure NuGet
  - mono ${NUGET_COMMAND} sources add -source ${NUGET_SOURCE} -name ${NUGET_NAME} -username gitlab-ci-token -password $CI_JOB_TOKEN

lint-clang-tidy:
  image: $CI_REGISTRY/asxa86/images/ubuntu-dev:latest
  stage: lint
  needs: []
  tags:
    # - saas-linux-medium-amd64
    - shelley
    - docker
    - large
  script:
    - *get-vcpkg

    # Configure Aspire
    - ${CMAKE_COMMAND} --preset x64-linux-gcc-debug

    # Build to force generate moc files.
    - ${CMAKE_COMMAND} --build --preset x64-linux-gcc-debug

    # Run Clang Tidy
    - find module/ app/ -type f -name "*.cpp" -print0 | xargs -0 -P $(nproc --all) clang-tidy-18 -p build

.build-base:
  image: $CI_REGISTRY/asxa86/images/ubuntu-dev:latest
  stage: build
  needs: []
  tags:
    # - saas-linux-medium-amd64
    - shelley
    - docker
    - large
  script:
    - *get-vcpkg

    # Build Aspire
    - ${CMAKE_COMMAND} --preset ${CMAKE_PRESET}
    - ${CMAKE_COMMAND} --build --preset ${CMAKE_PRESET}
  # artifacts:
  #   when: on_failure
  #   paths:
  #     - vcpkg/buildtrees/**/*.txt
  #     - vcpkg/buildtrees/**/*.log

build-gcc-debug:
  extends: .build-base
  variables:
    CMAKE_PRESET: x64-linux-gcc-debug
  artifacts:
    expire_in: 1 day
    paths:
      - build

build-gcc-release:
  extends: .build-base
  variables:
    CMAKE_PRESET: x64-linux-gcc-release
  artifacts:
    expire_in: 1 day
    paths:
      - build-release

build-android-x64-debug:
  image: $CI_REGISTRY/asxa86/images/android-build:latest
  extends: .build-base
  variables:
    CMAKE_PRESET: x64-android-debug
  artifacts:
    expire_in: 1 day
    paths:
      - build
    exclude:
      - build/vcpkg_installed/**/*

build-android-armg64-debug:
  image: $CI_REGISTRY/asxa86/images/android-build:latest
  extends: .build-base
  variables:
    CMAKE_PRESET: arm64-android-debug
  artifacts:
    expire_in: 1 day
    paths:
      - build
    exclude:
      - build/vcpkg_installed/**/*

build-gcc-debug-sonar:
  image: $CI_REGISTRY/asxa86/images/ubuntu-dev:latest
  stage: build
  needs: []
  tags:
    # - saas-linux-medium-amd64
    - shelley
    - docker
    - large
  variables:
    CMAKE_PRESET: x64-linux-gcc-debug
  script:
    # Download sonar-scanner
    - curl -sSLo ./sonar-scanner.zip 'https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.1.0.4477-linux-x64.zip'
    - unzip -o sonar-scanner.zip
    - mv sonar-scanner-6.1.0.4477-linux-x64 sonar-scanner
    # Download build-wrapper
    - curl -sSLo ./build-wrapper-linux-x86.zip "${SONAR_HOST_URL}/static/cpp/build-wrapper-linux-x86.zip"
    - unzip -oj build-wrapper-linux-x86.zip -d ./build-wrapper
    # Run the build inside the build wrapper
    - *get-vcpkg
    - ${CMAKE_COMMAND} --preset ${CMAKE_PRESET}
    - build-wrapper/build-wrapper-linux-x86-64 --out-dir bw-output ${CMAKE_COMMAND} --build --preset ${CMAKE_PRESET}
    # Run the sonar-scanner in the same stage as the build
    - sonar-scanner/bin/sonar-scanner -Dsonar.host.url="${SONAR_HOST_URL}" -Dsonar.token="${SONAR_TOKEN}" -Dsonar.cfamily.compile-commands=bw-output/compile_commands.json

test-gcc-debug:
  image: $CI_REGISTRY/asxa86/images/ubuntu-dev:latest
  stage: test
  needs:
    - build-gcc-debug
  tags:
    # - saas-linux-medium-amd64
    - shelley
    - docker
    - large
  script:
    - *get-vcpkg
    - ${CMAKE_COMMAND} --build --preset x64-linux-gcc-debug --target test
