stages:
  - dependencies
  - lint
  - build
  - test

vcpkg:
  image: ubuntu:latest
  stage: dependencies
  script:
    - apt update -y
    - apt install -y g++ curl tar git
    - git clone https://github.com/microsoft/vcpkg.git
    - cd vcpkg
    - ./bootstrap-vcpkg.sh
    
    - apt install ca-certificates gnupg
    - gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
    - echo "deb [signed-by=/usr/share/keyrings/mono-official-archive-keyring.gpg] https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
    - apt update
    - apt install -y mono-complete


lint-clang-format:
  image: ubuntu:latest
  stage: lint
  script:
    - echo "No Impl."