stages:
  - lint
  - build
  - test

lint-clang-format:
  image: ubuntu:latest
  stage: lint
  script:
    - echo "No Impl."

build-gcc-debug:
  image: ubuntu:latest
  stage: build
  needs: []
  script:
    # Install VCPKG
    - apt update -y
    - apt install -y g++ make
    - apt install -y libgl1-mesa-dev libglu1-mesa-dev
    - ./vcpkg/bootstrap-vcpkg.sh

    # Build Aspire
    - ${CMAKE_COMMAND} --build --preset gcc-debug
