stages:
  - lint
  - build
  - test

lint-clang-format:
  image: $BUILD_IMAGE
  stage: lint
  script:
    - echo "No Impl."

build-clang-tidy:
  image: $CI_REGISTRY/asxa86/images/ubuntu-clang:latest
  stage: build
  needs: []
  variables:
    CLANG_VERSION: 17
  script:
    # Install Dependencies
    - apt install -y make cmake
    - apt install -y libgl1-mesa-dev libglu1-mesa-dev

    # Run Clang Tidy
    - cmake --preset clang-debug
    - cd build
    - ls -al /usr/share
    - ls -al /usr/share/clang
    - /usr/share/clang/run-clang-tidy.py

build-gcc-debug:
  image: $CI_REGISTRY/asxa86/images/ubuntu-gcc:latest
  stage: build
  needs: []
  script:
    # Install Dependencies
    - apt install -y make cmake
    - apt install -y libgl1-mesa-dev libglu1-mesa-dev

    # Build
    - cmake --preset gcc-debug
    - cmake --build --preset gcc-debug
