stages:
  - lint
  - build
  - test

variables:
  NUGET_SOURCE: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/nuget/index.json"
  NUGET_NAME: gitlab
  VCPKG_VERSION: 2024.02.14
  VCPKG_BINARY_SOURCES: "clear;nuget,${NUGET_NAME},readwrite"
  CMAKE_COMMAND: ${CI_PROJECT_DIR}/vcpkg/downloads/tools/cmake-3.27.1-linux/cmake-3.27.1-linux-x86_64/bin/cmake
  NUGET_COMMAND: ${CI_PROJECT_DIR}/vcpkg/downloads/tools/nuget-6.2.1-linux/nuget.exe

lint-clang-format:
  image: $BUILD_IMAGE
  stage: lint
  script:
    - echo "No Impl."

build-clang-tidy:
  image: $CI_REGISTRY/asxa86/images/ubuntu-clang:latest
  stage: build
  needs: []
  script:
    # Install Dependencies
    - apt update -y
    - apt install -y make cmake python3
    - apt install -y libgl1-mesa-dev libglu1-mesa-dev

    # Run Clang Tidy
    - cmake --preset clang-debug
    - /usr/bin/run-clang-tidy -p build

build-gcc-debug:
  image: $CI_REGISTRY/asxa86/images/ubuntu-dev:latest
  stage: build
  needs: []
  script:
    # Get vcpkg
    - git clone https://github.com/microsoft/vcpkg.git --depth 1 --branch ${VCPKG_VERSION}
    - ./vcpkg/bootstrap-vcpkg.sh
    - ./vcpkg/vcpkg fetch nuget
    - ./vcpkg/vcpkg fetch cmake

    # Configure NuGet
    - mono ${NUGET_COMMAND} sources add -source ${NUGET_SOURCE} -name ${NUGET_NAME} -username gitlab-ci-token -password $CI_JOB_TOKEN

    # Build Aspire
    - ${CMAKE_COMMAND} --preset gcc-debug
    - ${CMAKE_COMMAND} --build --preset gcc-debug
  artifacts:
    when: on_failure
    paths:
      - vcpkg/buildtrees/**/*.txt
      - vcpkg/buildtrees/**/*.log