stages:
  - lint
  - build
  - test

lint-clang-format:
  image: ubuntu:latest
  stage: lint
  script:
    - echo "No Impl."

build-gcc-debug:
  image: ubuntu:latest
  stage: build
  needs: []
  script:
    - apt update -y

    # Install Tools
    - apt install -y g++ make cmake

    # Install Dependencies
    - apt install -y libgl1-mesa-dev libglu1-mesa-dev

    # Build
    - cmake --preset gcc-debug
    - cmake --build --preset gcc-debug
