
NUGET_COMMAND_PATH=$1
NUGET_PACKAGE_SOURCE=$2
NUGET_NAME=$3
GITLAB_USER=$4
GITLAB_TOKEN=$5

mono $NUGET_COMMAND_PATH sources add -source $NUGET_PACKAGE_SOURCE -name $NUGET_NAME -username $GITLAB_USER -password $GITLAB_TOKEN

